library("gap")
GLM=read.delim("PHEWAS_Basic_AgeSexPCAdj.CIincluded.Mapped",sep="\t",header=F)
png("Basic_GLM_PHEWAS_QQ.png",height=850,width=850)
gcontrol2(GLM$V14,pch=20,col=("steelblue"),lcol="steelblue4",cex=1.5,cex.lab=1.5,cex.axis=1.5)
dev.off()
l=gcontrol2(GLM$V14)
l1=as.data.frame(as.table(print(l$lambda)))
l1$Var1="Overall_Additive"
write.table(l1,"Lambda_Basic_GLM.txt")
